image:
  name: node:12-alpine

stages:
  - lint
  - health
  - tests

.api_test: &api_test
  stage: tests
  tags:
    - docker
    - tests
  allow_failure: true
  script:
    - npm i
    - npm run test
  artifacts:
    reports:
      junit: artifacts/test-output.xml

lint:
  stage: lint
  script:
   - npm i
   - npm run eslint

health:
  stage: health
  allow_failure: true
  script:
    - npm i
    - npm run test:health
  artifacts:
    reports:
      junit: artifacts/test-output.xml

banking:
  stage: tests
  when: manual
  script:
    - npm i
    - npm run test:banking

bets:
  stage: tests
  when: manual
  script:
    - npm i
    - npm run test:bets

user-profile:
  stage: tests
  when: manual
  script:
    - npm i
    - npm run test:user-profile

backend_staging:
  variables:
    TEST_URL: https://1win.dev/
    TEST_FILTER: "@master"
  <<: *api_test

#backend_production:
#  when: manual
#  variables:
#    TEST_URL: https://1winufeg.xyz/
#    TEST_FILTER: "@dev"
#  <<: *api_test
