image:
  name: node:12-alpine


variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - lint
  - health
  - tests

.api_test: &api_test
  stage: tests
  tags:
    - docker
  allow_failure: true
  before_script:
    - printf '@1win:registry=http://fbet-gitlab.ex2b.co:4873/\n//fbet-gitlab.ex2b.co:4873/:_authToken="LNQ2AYp7C5OLh7H0kO0VLg=="\n' > .npmrc
  script:
    - npm i
    - npm run test
  artifacts:
    reports:
      junit: artifacts/test-output.xml

lint:
  stage: lint
  script:
   - npm i
   - npm run eslint

health:
  stage: health
  allow_failure: true
  script:
    - npm i
    - npm run test:health
  artifacts:
    reports:
      junit: artifacts/test-output.xml

banking:
  stage: tests
  when: manual
  script:
    - npm i
    - npm run test:banking

bets:
  stage: tests
  when: manual
  script:
    - npm i
    - npm run test:bets

user-profile:
  stage: tests
  when: manual
  script:
    - npm i
    - npm run test:user-profile

backend_staging:
  variables:
    TEST_URL: https://1win.dev/
    TEST_FILTER: "@master"
  <<: *api_test

#backend_production:
#  when: manual
#  variables:
#    TEST_URL: https://1winufeg.xyz/
#    TEST_FILTER: "@dev"
#  <<: *api_test
