image:
  name: node:12-alpine

stages:
  - lint
  - health
  - tests

.api_test: &api_test
  stage: tests
  tags:
    - docker
    - tests
  allow_failure: true
  script:
    - npm i
    - npm run test-backend-auto
  artifacts:
    reports:
      junit: artifacts/test-output.xml

lint:
  stage: lint
  script:
   - npm i
   - npm run eslint

health:
  stage: health
  allow_failure: true
  tags:
    - docker
    - tests
  script:
    - npm i
    - npm run test:health
  artifacts:
    reports:
      junit: artifacts/test-output.xml

banking:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 6
    SCRIPT_NAME: 'banking'
  when: manual
  script:
    - npm i
    - npm run test:banking
  artifacts:
    reports:
      junit: artifacts/test-output.xml

bets:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 6
    SCRIPT_NAME: 'bets'
  when: manual
  script:
    - npm i
    - npm run test:bets
  artifacts:
    reports:
      junit: artifacts/bets-output.xml

bonus:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
    SCRIPT_NAME: 'bonus'
  when: manual
  script:
    - npm i
    - npm run test:bonus
  artifacts:
    reports:
      junit: artifacts/bets-output.xml

cases:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 6
    SCRIPT_NAME: 'cases'
  when: manual
  script:
    - npm i
    - npm run test:casino-jackpot

casino:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 6
    SCRIPT_NAME: 'casino'
  when: manual
  script:
    - npm i
    - npm run test:casino-jackpot

casino-jackpot:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
    SCRIPT_NAME: 'casino-jackpot'
  when: manual
  script:
    - npm i
    - npm run test:casino-jackpot

casino-poker:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
    SCRIPT_NAME: 'casino-poker'
  when: manual
  script:
    - npm i
    - npm run test:casino-poker

cinema:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
    SCRIPT_NAME: 'cinema'
  when: manual
  script:
    - npm i
    - npm run test:cinema

common:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
    SCRIPT_NAME: 'common'
  when: manual
  script:
    - npm i
    - npm run test:common

favourites:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
    SCRIPT_NAME: 'favourites'
  when: manual
  script:
    - npm i
    - npm run test:favourites

general:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
    SCRIPT_NAME: 'general'
  when: manual
  script:
    - npm i
    - npm run test:general

matchStorage:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
    SCRIPT_NAME: 'matchStorage'
  when: manual
  script:
    - npm i
    - npm run test:matchStorage

matchStorage2:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
    SCRIPT_NAME: 'matchStorage2'
  when: manual
  script:
    - npm i
    - npm run test:matchStorage2

matchTranslations:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
    SCRIPT_NAME: 'matchTranslations'
  when: manual
  script:
    - npm i
    - npm run test:matchtranslations

partner:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
    SCRIPT_NAME: 'partner'
  when: manual
  script:
    - npm i
    - npm run test:partner

recoupment:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 6
    SCRIPT_NAME: 'recoupment'
  when: manual
  script:
    - npm i
    - npm run test:recoupment

results:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
    SCRIPT_NAME: 'results'
  when: manual
  script:
    - npm i
    - npm run test:results

search:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
    SCRIPT_NAME: 'search'
  when: manual
  script:
    - npm i
    - npm run test:search

user-history:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
    SCRIPT_NAME: 'user-history'
  when: manual
  script:
    - npm i
    - npm run test:user-history

user-meta:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 6
    SCRIPT_NAME: 'user-meta'
  when: manual
  script:
    - npm i
    - npm run test:user-meta

user-profile:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 6
    SCRIPT_NAME: 'user-profile'
  when: manual
  script:
    - npm i
    - npm run test:user-profile

backend_staging:
  variables:
    TEST_URL: https://1win.dev/
    TEST_FILTER: "@master"
    CYPRESS_TESTRAIL_PROJECT_ID: 6
  <<: *api_test

#backend_production:
#  when: manual
#  variables:
#    TEST_URL: https://1winufeg.xyz/
#    TEST_FILTER: "@dev"
#  <<: *api_test
