image:
  name: node:12-alpine

stages:
  - lint
  - health
  - tests

.api_test: &api_test
  stage: tests
  tags:
    - docker
    - tests
  allow_failure: true
  script:
    - npm i
    - npm run test-backend-auto
  artifacts:
    reports:
      junit: artifacts/test-output.xml

lint:
  stage: lint
  script:
   - npm i
   - npm run eslint

health:
  stage: health
  allow_failure: true
  tags:
    - docker
    - tests
  script:
    - npm i
    - npm run test:health
  artifacts:
    reports:
      junit: artifacts/test-output.xml

banking:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 6
  when: manual
  script:
    - npm i
    - npm run test:banking
  artifacts:
    reports:
      junit: artifacts/test-output.xml

bets:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 6
  when: manual
  script:
    - npm i
    - npm run test:bets
  artifacts:
    reports:
      junit: artifacts/bets-output.xml

bonus:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
  when: manual
  script:
    - npm i
    - npm run test:bonus
  artifacts:
    reports:
      junit: artifacts/bets-output.xml

common:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
  when: manual
  script:
    - npm i
    - npm run test:common

general:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
  when: manual
  script:
    - npm i
    - npm run test:general

matchStorage:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
  when: manual
  script:
    - npm i
    - npm run test:matchStorage

matchStorage2:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
  when: manual
  script:
    - npm i
    - npm run test:matchStorage2

matchTranslations:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
  when: manual
  script:
    - npm i
    - npm run test:matchtranslations

partner:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
  when: manual
  script:
    - npm i
    - npm run test:partner

results:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
  when: manual
  script:
    - npm i
    - npm run test:results

user-history:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 4
  when: manual
  script:
    - npm i
    - npm run test:user-history

user-profile:
  stage: tests
  variables:
    CYPRESS_TESTRAIL_PROJECT_ID: 6
  when: manual
  script:
    - npm i
    - npm run test:user-profile

backend_staging:
  variables:
    TEST_URL: https://1win.dev/
    TEST_FILTER: "@master"
    CYPRESS_TESTRAIL_PROJECT_ID: 6
  <<: *api_test

#backend_production:
#  when: manual
#  variables:
#    TEST_URL: https://1winufeg.xyz/
#    TEST_FILTER: "@dev"
#  <<: *api_test
